### ISSUE TITLE
Undefined index and pass-by-reference errors on PHP 7

### ISSUE THREAD

**Issue by EiraStudios** [wp-id/hyperdrive#19]
While running the plugin on PHP 7 the following notice is thrown:
`Notice: Only variables should be passed by reference in /wp-content/plugins/hyperdrive/hyperdrive.php on line 156`

I also receive several undefined index errors:
`Notice: Undefined index: conditional in /wp-content/plugins/hyperdrive/hyperdrive.php on line 81`

**EDIT:** I just noticed empty strings were being added to the final JSON encoded _$fetch_inject_string_ variable used for the Fetch Injection. I've committed a fix for this too.

I've issued a pull request which resolves the above issues: #18

**Comment by jhabdas** [comment]
Closed with incorporation of changes from #18, now available in [`1.0.0-beta.2`](https://github.com/wp-id/hyperdrive/blob/master/CHANGELOG.md#100-beta2-2017-05-09)
